package:
  name: conda-pack
  version: 0.0.1

source:
  path: ../

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - setuptools
    - python
  run:
    - python
    - click

test:
  imports:
    - conda_pack

about:
  home: https://github.com/jcrist/conda-pack
  license: BSD 3-Clause
  license-family: BSD
  license_file: LICENSE.txt
  summary: A tool for packaging conda environments for redistribution
